AAAAAAAAAAAAAAAA

diff --git a/taskfile.yml b/taskfile.yml
--- a/taskfile.yml
+++ b/taskfile.yml
@@ -1,5 +1,5 @@
 # yaml-language-server: $schema=https://taskfile.dev/schema.json
-version: '3'
+version: "3"
 
 tasks:
   init:
@@ -7,17 +7,18 @@ tasks:
     cmds:
       - task: lefthook-install
       - task: lefthook-setup
+      - cmd: command -v gcc || echo "GCC not found (required for go-sqlite3); please install"
     method: none
 
   lefthook-install:
     desc: Install Lefthook if not already installed.
     cmd: |
-        if command -v lefthook >/dev/null 2>&1; then
-          echo "Lefthook already installed."
-        else
-          echo "Lefthook not found; installing via go install..."
-          go install github.com/evilmartians/lefthook/v2@latest
-        fi
+      if command -v lefthook >/dev/null 2>&1; then
+        echo "Lefthook already installed."
+      else
+        echo "Lefthook not found; installing via go install..."
+        go install github.com/evilmartians/lefthook/v2@latest
+      fi
     method: none
     internal: true
 
